export const webflowGuide = {
  platform: "Webflow",
  slug: "webflow",
  tagline: "The most GEO-capable no-code platform — comes closest to developer-level control.",
  geoScore: 81,
  color: "#4353ff",

  canDo: [
    {
      title: "Add JSON-LD Schema",
      difficulty: "easy",
      steps: [
        "In Webflow Designer, open Page Settings for the page you want to add schema to.",
        "Scroll to the 'Custom Code' section → 'Inside <head> tag' field.",
        "Paste your JSON-LD <script type='application/ld+json'> block.",
        "For CMS-powered pages (blog posts, products): use Webflow CMS fields as dynamic bindings.",
        "In the custom code field, reference CMS fields using Webflow's embed syntax or set up a CMS Embed element.",
        "For site-wide schema: Project Settings → Custom Code → Head Code section.",
        "Publish and validate with Google's Rich Results Test."
      ],
      tip: "Webflow's CMS lets you create a 'Schema' text field on any collection — paste the JSON-LD per item and embed it dynamically. This is the most scalable no-code schema approach available on any platform."
    },
    {
      title: "Edit Meta Title & Description",
      difficulty: "easy",
      steps: [
        "Static pages: Open Page Settings (gear icon) → SEO Settings tab.",
        "Edit Title Tag and Meta Description. Webflow shows character count warnings.",
        "CMS pages: Open the Collection's template page → Page Settings → SEO Settings.",
        "Bind fields dynamically: click the purple '+' icon next to each SEO field to bind to a CMS field.",
        "This means every blog post/product page gets its own unique meta automatically from CMS data.",
        "Publish to see changes live."
      ],
      tip: "Webflow's dynamic meta binding via CMS is a major GEO advantage — you can set up templates once and every new piece of content inherits optimized meta automatically."
    },
    {
      title: "robots.txt",
      difficulty: "easy",
      steps: [
        "Go to Project Settings → SEO tab.",
        "Scroll to the 'robots.txt' section — you get a full text editor.",
        "Write your custom robots.txt rules directly. Changes take effect on next publish.",
        "Add AI crawler rules: User-agent: GPTBot\nAllow: / \n\nUser-agent: ClaudeBot\nAllow: /",
        "You can also add crawl-delay directives and sitemap references here."
      ],
      tip: "Webflow is the only major no-code platform with a native robots.txt editor. This alone gives it a significant GEO edge over Wix, Squarespace, and even Shopify."
    },
    {
      title: "Open Graph Tags",
      difficulty: "easy",
      steps: [
        "Static pages: Page Settings → Open Graph Settings section.",
        "Set OG Title, OG Description, and upload an OG Image (1200×630px).",
        "CMS pages: bind OG fields to CMS data — every post gets its own OG image and copy automatically.",
        "Webflow also lets you set og:type, og:url, and twitter:card tags.",
        "Site-wide defaults: Project Settings → SEO → Default Open Graph image."
      ],
      tip: "Webflow's OG image binding to CMS is a superpower for content-heavy sites. Set up a Figma-based OG image template + Webflow's image field and every post gets branded social previews automatically."
    },
    {
      title: "Edit H1 & Content Headings",
      difficulty: "easy",
      steps: [
        "In the Webflow Designer, select any text element.",
        "In the left panel under Element Settings, choose the HTML tag: H1, H2, H3, H4, H5, H6, or paragraph.",
        "This sets the semantic HTML tag — completely separate from visual styling.",
        "Best practice: Style your headings visually however you want, but always set the correct semantic tag.",
        "Use the Webflow Audit tool (bottom toolbar) to check for missing alt tags, multiple H1s, and heading hierarchy errors."
      ],
      tip: "Webflow's separation of visual styling from HTML semantics is its biggest advantage over all other no-code tools. You can make an H3 look huge visually while keeping proper document structure for AI engines."
    },
    {
      title: "Canonical Tags & hreflang",
      difficulty: "medium",
      steps: [
        "Canonical tags are auto-generated by Webflow for all pages — pointing to the live URL.",
        "To override: Page Settings → SEO → Custom Canonical URL field.",
        "For hreflang (multilingual): add a custom code embed in the <head> with your hreflang link tags.",
        "Webflow Localization (their built-in multilingual feature) handles hreflang automatically if you use it."
      ],
      tip: "Custom canonical control is another area where Webflow pulls ahead of Wix and Squarespace."
    }
  ],

  cannotDo: [
    "Run custom server-side code or API routes — Webflow is a static site host (though you can use Webflow Logic for some automation).",
    "Implement server-side rendering with dynamic data fetching at request time (use Webflow + a headless approach for this).",
    "Achieve Next.js-level performance optimization — Webflow's generated code is clean but not hand-tuned.",
    "Build complex web applications with authenticated dynamic content (beyond Webflow's Memberships beta).",
    "Self-host — you're locked to Webflow's infrastructure."
  ],

  recommendedApps: [
    {
      name: "Finsweet Attributes",
      purpose: "Extends Webflow CMS with filtering, sorting, and dynamic rendering — great for large content sites.",
      free: true,
      url: "https://finsweet.com/attributes"
    },
    {
      name: "Whalesync",
      purpose: "Sync Airtable/Notion data to Webflow CMS — enables programmatic SEO at scale.",
      free: false,
      url: "https://whalesync.com"
    },
    {
      name: "Webflow Localization",
      purpose: "Native multilingual support with automatic hreflang — essential for international GEO.",
      free: false,
      url: "https://webflow.com/localization"
    }
  ],

  migrationFramework: {
    stayIf: [
      "You're a marketing-led company (agency, SaaS marketing site, professional services) where design + GEO control both matter.",
      "You have a content marketing strategy and want programmatic SEO without writing code.",
      "Your team includes non-developers who need to maintain the site — Webflow's Designer is the best no-code tool for GEO.",
      "You're already on Webflow — the GEO ceiling here is much higher than other no-code platforms."
    ],
    migrateIf: [
      "You need a full-stack web application with server-side logic (APIs, authentication, real-time data).",
      "You're hitting Webflow CMS limits (10,000 items per collection) and need a custom database.",
      "You need sub-1s LCP or advanced Core Web Vitals optimization that Webflow's output can't achieve.",
      "Your team is developer-heavy and the Designer UI is more hindrance than help."
    ],
    recommendedAlternative: "Next.js with a headless CMS (Contentful, Sanity, or Notion API) — preserves content flexibility while giving full technical control."
  }
};
