export interface BlogPost {
  slug:        string
  title:       string
  description: string
  date:        string
  lastMod:     string
  readTime:    string
  tag:         string
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug:        'what-is-geo',
    title:       "What is GEO? The Beginner's Guide to Generative Engine Optimization",
    description: "Traditional SEO gets you on Google. GEO gets you cited in AI answers. Here's what it is, why it matters, and how to start.",
    date:        'May 10, 2026',
    lastMod:     '2026-05-10',
    readTime:    '5 min read',
    tag:         'GEO Basics',
  },
  {
    slug:        'geo-vs-seo',
    title:       'GEO vs SEO: What Is the Difference?',
    description: 'SEO and GEO both help people find your business — but they work on completely different surfaces, with different signals. Here is how they compare and why you need both.',
    date:        'May 20, 2026',
    lastMod:     '2026-05-20',
    readTime:    '6 min read',
    tag:         'GEO Basics',
  },
  {
    slug:        'does-my-business-need-geo',
    title:       'Does My Business Need GEO?',
    description: "Not every business has the same urgency around AI visibility — but most do. Here's how to tell if GEO should be a priority for you right now.",
    date:        'May 21, 2026',
    lastMod:     '2026-05-21',
    readTime:    '5 min read',
    tag:         'GEO Basics',
  },
  {
    slug:        'how-long-does-geo-take',
    title:       'How Long Does GEO Take to Work?',
    description: "GEO isn't instant — but it's also not as slow as traditional SEO. Here's a realistic timeline for when you can expect to start appearing in AI-generated answers.",
    date:        'May 22, 2026',
    lastMod:     '2026-05-22',
    readTime:    '5 min read',
    tag:         'GEO Basics',
  },
  {
    slug:        'geo-for-beginners-checklist',
    title:       'GEO Checklist for Beginners: 10 Things to Do in Your First 30 Days',
    description: "New to GEO? Here's a practical, prioritized checklist of the 10 highest-impact actions you can take in your first month to start building AI visibility.",
    date:        'May 28, 2026',
    lastMod:     '2026-05-28',
    readTime:    '6 min read',
    tag:         'GEO Basics',
  },
  {
    slug:        'what-is-ai-visibility',
    title:       'What Is AI Visibility and Why Does It Matter for Your Business?',
    description: 'AI visibility is how often and how prominently your business appears when AI tools like ChatGPT, Perplexity, and Gemini answer questions in your category. Here is why it is becoming a critical business metric.',
    date:        'May 29, 2026',
    lastMod:     '2026-05-29',
    readTime:    '5 min read',
    tag:         'GEO Basics',
  },
  {
    slug:        'ai-search-guide',
    title:       'How AI Search Engines Decide Which Businesses to Mention',
    description: "ChatGPT, Perplexity and Gemini don't rank websites — they generate answers. Here's exactly how they decide who gets cited.",
    date:        'May 12, 2026',
    lastMod:     '2026-05-12',
    readTime:    '7 min read',
    tag:         'AI Search',
  },
  {
    slug:        'ai-search-vs-google-search',
    title:       'AI Search vs. Google Search: What Is Actually Changing?',
    description: 'AI search and Google search feel similar but work completely differently. Here is an honest breakdown of what is changing and what it means for your business.',
    date:        'May 23, 2026',
    lastMod:     '2026-05-23',
    readTime:    '7 min read',
    tag:         'AI Search',
  },
  {
    slug:        'perplexity-vs-chatgpt-visibility',
    title:       'Perplexity vs. ChatGPT: Do You Show Up Differently on Each?',
    description: 'Your business may appear in ChatGPT answers but not Perplexity — or vice versa. Here is why the two platforms surface different results and what you can do about it.',
    date:        'May 23, 2026',
    lastMod:     '2026-05-23',
    readTime:    '6 min read',
    tag:         'AI Search',
  },
  {
    slug:        'ai-search-zero-click',
    title:       "The Zero-Click AI Era: Why Getting Traffic Now Requires Being the Answer",
    description: "AI search doesn't send clicks — it gives answers. If your business isn't mentioned in those answers, you're invisible. Here's what zero-click AI means for your growth strategy.",
    date:        'May 11, 2026',
    lastMod:     '2026-05-11',
    readTime:    '7 min read',
    tag:         'AI Search',
  },
  {
    slug:        'how-gemini-ranks-local-businesses',
    title:       'How Google Gemini Ranks Local Businesses in AI Answers',
    description: 'Google Gemini has more access to local business data than any other AI tool. Here is exactly how it decides which businesses to surface — and what you need to do to appear.',
    date:        'May 27, 2026',
    lastMod:     '2026-05-27',
    readTime:    '7 min read',
    tag:         'AI Search',
  },
  {
    slug:        'geo-score-benchmarks',
    title:       "What's a Good GEO Score? Industry Benchmarks for 2026",
    description: 'Most businesses score below 30 out of 100 on AI visibility. Here are real benchmark data points across industries — and what score you actually need to compete.',
    date:        'May 13, 2026',
    lastMod:     '2026-05-13',
    readTime:    '6 min read',
    tag:         'Strategy',
  },
  {
    slug:        'geo-for-saas',
    title:       'GEO for SaaS: How Software Companies Should Think About AI Visibility',
    description: 'When someone asks ChatGPT to recommend a project management tool or CRM, which software gets named? Here is how SaaS companies can build AI visibility.',
    date:        'May 23, 2026',
    lastMod:     '2026-05-23',
    readTime:    '7 min read',
    tag:         'Strategy',
  },
  {
    slug:        'geo-before-launch',
    title:       'Launch Day GEO: How to Set Up AI Visibility Before Your Business Goes Live',
    description: "Most new businesses lose their first 90 days of AI visibility by doing nothing. Here's how to build your GEO foundation before you open — so you show up from day one.",
    date:        'May 9, 2026',
    lastMod:     '2026-05-09',
    readTime:    '6 min read',
    tag:         'Strategy',
  },
  {
    slug:        'geo-roi',
    title:       'What Is the ROI of GEO? How to Measure AI Visibility Impact on Revenue',
    description: 'GEO is not just a vanity metric. Here is how to measure the real business impact of improving your AI visibility score — and what ROI looks like at different business sizes.',
    date:        'May 26, 2026',
    lastMod:     '2026-05-26',
    readTime:    '7 min read',
    tag:         'Strategy',
  },
  {
    slug:        'geo-competitive-analysis',
    title:       'GEO Competitive Analysis: How to See Where You Stand vs. Your Competitors on AI',
    description: "Your competitors are either ahead or behind you on AI visibility — and most businesses have no idea where they stand. Here's how to run a proper GEO competitive analysis.",
    date:        'May 30, 2026',
    lastMod:     '2026-05-30',
    readTime:    '6 min read',
    tag:         'Strategy',
  },
  {
    slug:        'google-business-profile-geo',
    title:       'Why Google Business Profile Is Your Most Important GEO Asset',
    description: 'AI assistants like ChatGPT and Perplexity rely heavily on Google Business Profile data when answering local queries. Here is why it matters and what your profile needs to include.',
    date:        'May 23, 2026',
    lastMod:     '2026-05-23',
    readTime:    '6 min read',
    tag:         'Local GEO',
  },
  {
    slug:        'multi-location-geo',
    title:       'Multi-Location GEO: How Chains and Franchises Should Handle AI Visibility',
    description: "Single-location GEO is straightforward. Managing AI visibility across 10, 50, or 500 locations is a different challenge entirely. Here's the right architecture.",
    date:        'May 7, 2026',
    lastMod:     '2026-05-07',
    readTime:    '8 min read',
    tag:         'Local GEO',
  },
  {
    slug:        'nap-consistency-geo',
    title:       'NAP Consistency and GEO: Why Your Name, Address, and Phone Number Matter More Than Ever',
    description: 'AI models cross-reference your business information across dozens of sources. A single inconsistency in your name, address, or phone number can suppress your visibility. Here is how to fix it.',
    date:        'May 25, 2026',
    lastMod:     '2026-05-25',
    readTime:    '6 min read',
    tag:         'Local GEO',
  },
  {
    slug:        'schema-markup-for-geo',
    title:       'Schema Markup and GEO: Why Structured Data Is Critical for AI Visibility',
    description: 'Schema markup is one of the most direct signals you can give AI assistants about who your business is. Here is what it is, why it matters for GEO, and which types to prioritize.',
    date:        'May 23, 2026',
    lastMod:     '2026-05-23',
    readTime:    '7 min read',
    tag:         'Technical GEO',
  },
  {
    slug:        'ai-hallucination-fix',
    title:       'When AI Gets Your Business Wrong: How to Fix AI Hallucinations About Your Company',
    description: "AI engines sometimes generate confidently wrong information about businesses — wrong hours, wrong address, wrong services. Here's how to find it and fix it before it costs you customers.",
    date:        'May 5, 2026',
    lastMod:     '2026-05-05',
    readTime:    '7 min read',
    tag:         'Technical GEO',
  },
  {
    slug:        'llms-txt-guide',
    title:       'What Is llms.txt and Does Your Business Website Need One?',
    description: 'llms.txt is an emerging standard that tells AI crawlers what to read on your website. Here is what it is, how it works, and whether you need to add one to your site.',
    date:        'May 24, 2026',
    lastMod:     '2026-05-24',
    readTime:    '6 min read',
    tag:         'Technical GEO',
  },
  {
    slug:        'reviews-and-geo',
    title:       'How Online Reviews Directly Impact Your AI Visibility Score',
    description: 'AI tools read and summarize your reviews to decide how authoritative your business is. Here is the direct link between review quantity, recency, and your GEO score.',
    date:        'May 15, 2026',
    lastMod:     '2026-05-15',
    readTime:    '6 min read',
    tag:         'Reviews & Citations',
  },
  {
    slug:        'how-to-get-more-google-reviews',
    title:       'How to Get More Google Reviews (That Actually Improve Your AI Visibility)',
    description: 'Volume and recency of Google reviews are two of the strongest GEO signals. Here is a practical playbook for getting more reviews without violating Google policy.',
    date:        'May 16, 2026',
    lastMod:     '2026-05-16',
    readTime:    '7 min read',
    tag:         'Reviews & Citations',
  },
  {
    slug:        'citation-building-for-geo',
    title:       'Citation Building for GEO: Which Directories Actually Matter for AI Visibility',
    description: "Not all directory listings are equal. Here's which citation sources carry the most weight with AI models in 2026 — and which ones you can safely skip.",
    date:        'May 17, 2026',
    lastMod:     '2026-05-17',
    readTime:    '7 min read',
    tag:         'Reviews & Citations',
  },
]

export const BLOG_TAGS = ['All', ...Array.from(new Set(BLOG_POSTS.map(p => p.tag)))]
