export interface City {
  slug: string
  name: string
  state: string
  stateAbbr: string
  population: number
}

export const CITIES: City[] = [
  { slug: 'new-york-ny', name: 'New York', state: 'New York', stateAbbr: 'NY', population: 8336817 },
  { slug: 'los-angeles-ca', name: 'Los Angeles', state: 'California', stateAbbr: 'CA', population: 3979576 },
  { slug: 'chicago-il', name: 'Chicago', state: 'Illinois', stateAbbr: 'IL', population: 2693976 },
  { slug: 'houston-tx', name: 'Houston', state: 'Texas', stateAbbr: 'TX', population: 2320268 },
  { slug: 'phoenix-az', name: 'Phoenix', state: 'Arizona', stateAbbr: 'AZ', population: 1680992 },
  { slug: 'philadelphia-pa', name: 'Philadelphia', state: 'Pennsylvania', stateAbbr: 'PA', population: 1584064 },
  { slug: 'san-antonio-tx', name: 'San Antonio', state: 'Texas', stateAbbr: 'TX', population: 1547253 },
  { slug: 'san-diego-ca', name: 'San Diego', state: 'California', stateAbbr: 'CA', population: 1423851 },
  { slug: 'dallas-tx', name: 'Dallas', state: 'Texas', stateAbbr: 'TX', population: 1343573 },
  { slug: 'san-jose-ca', name: 'San Jose', state: 'California', stateAbbr: 'CA', population: 1021795 },
  { slug: 'austin-tx', name: 'Austin', state: 'Texas', stateAbbr: 'TX', population: 978908 },
  { slug: 'jacksonville-fl', name: 'Jacksonville', state: 'Florida', stateAbbr: 'FL', population: 949611 },
  { slug: 'fort-worth-tx', name: 'Fort Worth', state: 'Texas', stateAbbr: 'TX', population: 918915 },
  { slug: 'columbus-oh', name: 'Columbus', state: 'Ohio', stateAbbr: 'OH', population: 905748 },
  { slug: 'charlotte-nc', name: 'Charlotte', state: 'North Carolina', stateAbbr: 'NC', population: 897720 },
  { slug: 'indianapolis-in', name: 'Indianapolis', state: 'Indiana', stateAbbr: 'IN', population: 887642 },
  { slug: 'san-francisco-ca', name: 'San Francisco', state: 'California', stateAbbr: 'CA', population: 881549 },
  { slug: 'seattle-wa', name: 'Seattle', state: 'Washington', stateAbbr: 'WA', population: 753675 },
  { slug: 'denver-co', name: 'Denver', state: 'Colorado', stateAbbr: 'CO', population: 727211 },
  { slug: 'nashville-tn', name: 'Nashville', state: 'Tennessee', stateAbbr: 'TN', population: 689447 },
  { slug: 'boston-ma', name: 'Boston', state: 'Massachusetts', stateAbbr: 'MA', population: 675647 },
  { slug: 'miami-fl', name: 'Miami', state: 'Florida', stateAbbr: 'FL', population: 467963 },
  { slug: 'atlanta-ga', name: 'Atlanta', state: 'Georgia', stateAbbr: 'GA', population: 498715 },
  { slug: 'portland-or', name: 'Portland', state: 'Oregon', stateAbbr: 'OR', population: 652503 },
  { slug: 'las-vegas-nv', name: 'Las Vegas', state: 'Nevada', stateAbbr: 'NV', population: 651319 },
  { slug: 'memphis-tn', name: 'Memphis', state: 'Tennessee', stateAbbr: 'TN', population: 633104 },
  { slug: 'louisville-ky', name: 'Louisville', state: 'Kentucky', stateAbbr: 'KY', population: 633045 },
  { slug: 'baltimore-md', name: 'Baltimore', state: 'Maryland', stateAbbr: 'MD', population: 585708 },
  { slug: 'milwaukee-wi', name: 'Milwaukee', state: 'Wisconsin', stateAbbr: 'WI', population: 577222 },
  { slug: 'albuquerque-nm', name: 'Albuquerque', state: 'New Mexico', stateAbbr: 'NM', population: 564559 },
  { slug: 'tucson-az', name: 'Tucson', state: 'Arizona', stateAbbr: 'AZ', population: 542629 },
  { slug: 'fresno-ca', name: 'Fresno', state: 'California', stateAbbr: 'CA', population: 530093 },
  { slug: 'mesa-az', name: 'Mesa', state: 'Arizona', stateAbbr: 'AZ', population: 504258 },
  { slug: 'sacramento-ca', name: 'Sacramento', state: 'California', stateAbbr: 'CA', population: 513624 },
  { slug: 'kansas-city-mo', name: 'Kansas City', state: 'Missouri', stateAbbr: 'MO', population: 508090 },
  { slug: 'long-beach-ca', name: 'Long Beach', state: 'California', stateAbbr: 'CA', population: 466742 },
  { slug: 'raleigh-nc', name: 'Raleigh', state: 'North Carolina', stateAbbr: 'NC', population: 467665 },
  { slug: 'omaha-ne', name: 'Omaha', state: 'Nebraska', stateAbbr: 'NE', population: 486051 },
  { slug: 'colorado-springs-co', name: 'Colorado Springs', state: 'Colorado', stateAbbr: 'CO', population: 472688 },
  { slug: 'minneapolis-mn', name: 'Minneapolis', state: 'Minnesota', stateAbbr: 'MN', population: 429606 },
  { slug: 'tampa-fl', name: 'Tampa', state: 'Florida', stateAbbr: 'FL', population: 399700 },
  { slug: 'new-orleans-la', name: 'New Orleans', state: 'Louisiana', stateAbbr: 'LA', population: 390845 },
  { slug: 'cleveland-oh', name: 'Cleveland', state: 'Ohio', stateAbbr: 'OH', population: 372624 },
  { slug: 'pittsburgh-pa', name: 'Pittsburgh', state: 'Pennsylvania', stateAbbr: 'PA', population: 302971 },
  { slug: 'orlando-fl', name: 'Orlando', state: 'Florida', stateAbbr: 'FL', population: 307573 },
  { slug: 'st-louis-mo', name: 'St. Louis', state: 'Missouri', stateAbbr: 'MO', population: 301578 },
  { slug: 'richmond-va', name: 'Richmond', state: 'Virginia', stateAbbr: 'VA', population: 226610 },
  { slug: 'salt-lake-city-ut', name: 'Salt Lake City', state: 'Utah', stateAbbr: 'UT', population: 199723 },
  { slug: 'birmingham-al', name: 'Birmingham', state: 'Alabama', stateAbbr: 'AL', population: 212237 },
  { slug: 'hartford-ct', name: 'Hartford', state: 'Connecticut', stateAbbr: 'CT', population: 121054 },
  // --- Expanded: 50 additional cities ---
  { slug: 'virginia-beach-va', name: 'Virginia Beach', state: 'Virginia', stateAbbr: 'VA', population: 459470 },
  { slug: 'el-paso-tx', name: 'El Paso', state: 'Texas', stateAbbr: 'TX', population: 678815 },
  { slug: 'oklahoma-city-ok', name: 'Oklahoma City', state: 'Oklahoma', stateAbbr: 'OK', population: 649021 },
  { slug: 'detroit-mi', name: 'Detroit', state: 'Michigan', stateAbbr: 'MI', population: 672662 },
  { slug: 'tucson-az-2', name: 'Tucson', state: 'Arizona', stateAbbr: 'AZ', population: 542629 },
  { slug: 'aurora-co', name: 'Aurora', state: 'Colorado', stateAbbr: 'CO', population: 366623 },
  { slug: 'corpus-christi-tx', name: 'Corpus Christi', state: 'Texas', stateAbbr: 'TX', population: 326586 },
  { slug: 'riverside-ca', name: 'Riverside', state: 'California', stateAbbr: 'CA', population: 314998 },
  { slug: 'lexington-ky', name: 'Lexington', state: 'Kentucky', stateAbbr: 'KY', population: 323780 },
  { slug: 'henderson-nv', name: 'Henderson', state: 'Nevada', stateAbbr: 'NV', population: 320189 },
  { slug: 'stockton-ca', name: 'Stockton', state: 'California', stateAbbr: 'CA', population: 312697 },
  { slug: 'st-paul-mn', name: 'St. Paul', state: 'Minnesota', stateAbbr: 'MN', population: 308096 },
  { slug: 'anchorage-ak', name: 'Anchorage', state: 'Alaska', stateAbbr: 'AK', population: 291538 },
  { slug: 'plano-tx', name: 'Plano', state: 'Texas', stateAbbr: 'TX', population: 288061 },
  { slug: 'newark-nj', name: 'Newark', state: 'New Jersey', stateAbbr: 'NJ', population: 282529 },
  { slug: 'greensboro-nc', name: 'Greensboro', state: 'North Carolina', stateAbbr: 'NC', population: 299035 },
  { slug: 'buffalo-ny', name: 'Buffalo', state: 'New York', stateAbbr: 'NY', population: 255284 },
  { slug: 'lincoln-ne', name: 'Lincoln', state: 'Nebraska', stateAbbr: 'NE', population: 289102 },
  { slug: 'durham-nc', name: 'Durham', state: 'North Carolina', stateAbbr: 'NC', population: 278993 },
  { slug: 'chandler-az', name: 'Chandler', state: 'Arizona', stateAbbr: 'AZ', population: 261165 },
  { slug: 'fort-wayne-in', name: 'Fort Wayne', state: 'Indiana', stateAbbr: 'IN', population: 263886 },
  { slug: 'jersey-city-nj', name: 'Jersey City', state: 'New Jersey', stateAbbr: 'NJ', population: 262075 },
  { slug: 'st-petersburg-fl', name: 'St. Petersburg', state: 'Florida', stateAbbr: 'FL', population: 258308 },
  { slug: 'laredo-tx', name: 'Laredo', state: 'Texas', stateAbbr: 'TX', population: 255205 },
  { slug: 'norfolk-va', name: 'Norfolk', state: 'Virginia', stateAbbr: 'VA', population: 244703 },
  { slug: 'madison-wi', name: 'Madison', state: 'Wisconsin', stateAbbr: 'WI', population: 269840 },
  { slug: 'lubbock-tx', name: 'Lubbock', state: 'Texas', stateAbbr: 'TX', population: 258862 },
  { slug: 'winston-salem-nc', name: 'Winston-Salem', state: 'North Carolina', stateAbbr: 'NC', population: 249545 },
  { slug: 'garland-tx', name: 'Garland', state: 'Texas', stateAbbr: 'TX', population: 234566 },
  { slug: 'baton-rouge-la', name: 'Baton Rouge', state: 'Louisiana', stateAbbr: 'LA', population: 227470 },
  { slug: 'scottsdale-az', name: 'Scottsdale', state: 'Arizona', stateAbbr: 'AZ', population: 258069 },
  { slug: 'glendale-az', name: 'Glendale', state: 'Arizona', stateAbbr: 'AZ', population: 248325 },
  { slug: 'reno-nv', name: 'Reno', state: 'Nevada', stateAbbr: 'NV', population: 255601 },
  { slug: 'hialeah-fl', name: 'Hialeah', state: 'Florida', stateAbbr: 'FL', population: 223109 },
  { slug: 'irvine-ca', name: 'Irvine', state: 'California', stateAbbr: 'CA', population: 307670 },
  { slug: 'chesapeake-va', name: 'Chesapeake', state: 'Virginia', stateAbbr: 'VA', population: 244835 },
  { slug: 'spokane-wa', name: 'Spokane', state: 'Washington', stateAbbr: 'WA', population: 222081 },
  { slug: 'gilbert-az', name: 'Gilbert', state: 'Arizona', stateAbbr: 'AZ', population: 267918 },
  { slug: 'fremont-ca', name: 'Fremont', state: 'California', stateAbbr: 'CA', population: 230504 },
  { slug: 'tacoma-wa', name: 'Tacoma', state: 'Washington', stateAbbr: 'WA', population: 219346 },
  { slug: 'san-bernardino-ca', name: 'San Bernardino', state: 'California', stateAbbr: 'CA', population: 216995 },
  { slug: 'irving-tx', name: 'Irving', state: 'Texas', stateAbbr: 'TX', population: 256684 },
  { slug: 'boise-id', name: 'Boise', state: 'Idaho', stateAbbr: 'ID', population: 235684 },
  { slug: 'birmingham-al-2', name: 'Birmingham', state: 'Alabama', stateAbbr: 'AL', population: 212237 },
  { slug: 'rochester-ny', name: 'Rochester', state: 'New York', stateAbbr: 'NY', population: 206284 },
  { slug: 'fayetteville-nc', name: 'Fayetteville', state: 'North Carolina', stateAbbr: 'NC', population: 211657 },
  { slug: 'des-moines-ia', name: 'Des Moines', state: 'Iowa', stateAbbr: 'IA', population: 214237 },
  { slug: 'akron-oh', name: 'Akron', state: 'Ohio', stateAbbr: 'OH', population: 190469 },
  { slug: 'yonkers-ny', name: 'Yonkers', state: 'New York', stateAbbr: 'NY', population: 211569 },
  { slug: 'montgomery-al', name: 'Montgomery', state: 'Alabama', stateAbbr: 'AL', population: 199518 },
]

export function getCityBySlug(slug: string): City | undefined {
  return CITIES.find(c => c.slug === slug)
}

export const TOP_20_CITIES = CITIES.slice(0, 20)
