export interface Comparison {
  slug: string
  title: string
  metaTitle: string
  metaDescription: string
  entityA: string
  entityB: string
  summary: string
  points: { label: string; a: string; b: string }[]
  verdict: string
  ctaText: string
}

export const COMPARISONS: Comparison[] = [
  {
    slug: 'geo-vs-seo',
    title: 'GEO vs SEO: What\'s the Difference?',
    metaTitle: 'GEO vs SEO: Key Differences Explained | MyGeoRadar',
    metaDescription: 'GEO and SEO both drive business visibility, but they work very differently. Learn which one your business needs in 2026.',
    entityA: 'GEO',
    entityB: 'SEO',
    summary: 'SEO gets your website ranked on Google. GEO gets your business recommended by AI tools like ChatGPT and Perplexity. In 2026, you need both.',
    points: [
      { label: 'Goal', a: 'Appear in AI-generated answers', b: 'Rank high in search engine results' },
      { label: 'Primary channel', a: 'ChatGPT, Perplexity, Gemini, Claude', b: 'Google, Bing' },
      { label: 'What signals matter', a: 'Reviews, citations, structured data, AI-readable content', b: 'Backlinks, keywords, page speed, technical optimization' },
      { label: 'Traffic type', a: 'Direct AI referrals, zero-click recommendations', b: 'Click-through traffic to your website' },
      { label: 'Time to results', a: '60–90 days for score improvements', b: '3–6 months for ranking gains' },
      { label: 'Cost to start', a: 'Free fixes + optional $29.99 audit', b: 'Free fixes or paid agency ($500–$5K+/mo)' },
    ],
    verdict: 'Do both. SEO builds website traffic; GEO captures the growing share of discovery happening inside AI assistants. Businesses that master both will dominate local search in the AI era.',
    ctaText: 'Get Your Free AI Visibility Score',
  },
  {
    slug: 'chatgpt-vs-google-for-local-search',
    title: 'ChatGPT vs Google for Local Business Search',
    metaTitle: 'ChatGPT vs Google: Which Drives More Local Business Leads? | MyGeoRadar',
    metaDescription: 'More consumers are using ChatGPT instead of Google to find local businesses. Here\'s how the two compare and what it means for your business.',
    entityA: 'ChatGPT',
    entityB: 'Google',
    summary: 'Google still handles the majority of searches, but ChatGPT is growing rapidly for local business discovery — especially among high-intent buyers.',
    points: [
      { label: 'User intent', a: 'Direct recommendation request', b: 'Research and comparison' },
      { label: 'Result format', a: 'Conversational answer with business names', b: 'List of links and map pack' },
      { label: 'Click behavior', a: 'User acts on the recommendation directly', b: 'User clicks through to compare websites' },
      { label: 'How to appear', a: 'GEO: reviews, citations, structured content', b: 'SEO: keywords, links, GMB optimization' },
      { label: 'Personalization', a: 'Can factor in location and preferences from context', b: 'Location-based results from IP/device' },
      { label: 'Trust signal', a: 'Being named by AI implies authority', b: 'High ranking implies authority' },
    ],
    verdict: 'Optimize for both. Google Maps and organic rankings still deliver volume. But the quality of leads from AI-driven recommendations tends to be higher because the user arrives with a specific intent.',
    ctaText: 'See How Visible You Are on Both',
  },
  {
    slug: 'mygeoradar-vs-traditional-seo-audit',
    title: 'MyGeoRadar vs Traditional SEO Audit Tools',
    metaTitle: 'MyGeoRadar vs SEO Audit Tools: What\'s the Difference? | MyGeoRadar',
    metaDescription: 'Traditional SEO audit tools check your website for Google. MyGeoRadar checks how visible your business is to AI. Here\'s the difference.',
    entityA: 'MyGeoRadar',
    entityB: 'Traditional SEO Audits',
    summary: 'SEO audit tools like Semrush and Ahrefs tell you how to rank on Google. MyGeoRadar tells you how visible you are when AI tools answer local search queries.',
    points: [
      { label: 'What it measures', a: 'AI visibility across ChatGPT, Perplexity, Gemini, Claude', b: 'Keyword rankings, backlinks, technical site health' },
      { label: 'Scan method', a: 'Queries live AI engines with real search terms', b: 'Crawls your website and checks SEO metrics' },
      { label: 'Output', a: 'AI Visibility Score + prioritized fix playbook', b: 'Technical issues list + keyword opportunities' },
      { label: 'Time to complete', a: 'Under 5 minutes', b: '30 minutes to hours depending on site size' },
      { label: 'Price', a: '$29.99 one-time per scan', b: '$99–$499/month for leading tools' },
      { label: 'Best for', a: 'Local businesses wanting AI discovery', b: 'Businesses focused on Google traffic' },
    ],
    verdict: 'Use MyGeoRadar alongside your existing SEO tools. They answer different questions. SEO tools optimize for Google; MyGeoRadar optimizes for the AI layer that is increasingly mediating how consumers find local businesses.',
    ctaText: 'Run Your AI Visibility Scan',
  },
  {
    slug: 'perplexity-vs-chatgpt-for-business-visibility',
    title: 'Perplexity vs ChatGPT: Which AI Matters More for Business Visibility?',
    metaTitle: 'Perplexity vs ChatGPT for Business Visibility | MyGeoRadar',
    metaDescription: 'Perplexity and ChatGPT both influence local business discovery. Here\'s how they differ and why you need visibility on both.',
    entityA: 'Perplexity',
    entityB: 'ChatGPT',
    summary: 'Both Perplexity and ChatGPT are used by consumers to find local businesses, but they work differently and require different optimization strategies.',
    points: [
      { label: 'How it finds information', a: 'Real-time web search with citations', b: 'Training data + optional browsing' },
      { label: 'User type', a: 'Research-focused, fact-checking users', b: 'General consumers, quick recommendation seekers' },
      { label: 'Citation behavior', a: 'Always shows sources', b: 'Varies by query and model version' },
      { label: 'How to appear', a: 'Current web presence, authoritative pages', b: 'Broad web signals in training data' },
      { label: 'User intent quality', a: 'High — users want sourced, accurate results', b: 'High — users want fast, direct answers' },
      { label: 'Growth rate', a: 'Fastest growing AI search tool in 2025–26', b: 'Largest user base overall' },
    ],
    verdict: 'Both matter. Perplexity favors businesses with current, crawlable web content. ChatGPT draws from broader training data. A complete GEO strategy addresses both with strong web presence and consistent, authoritative content.',
    ctaText: 'Check Your Visibility on Both Engines',
  },
  {
    slug: 'local-seo-vs-geo',
    title: 'Local SEO vs GEO: Which Drives More Local Business Leads?',
    metaTitle: 'Local SEO vs GEO: Which One Should Local Businesses Prioritize? | MyGeoRadar',
    metaDescription: 'Local SEO and GEO both drive local business leads, but they work on different channels. Here\'s how to think about both in 2026.',
    entityA: 'GEO',
    entityB: 'Local SEO',
    summary: 'Local SEO targets Google Maps and local organic rankings. GEO targets AI-generated recommendations. Both are important — but GEO is where early movers gain the biggest edge.',
    points: [
      { label: 'Primary target', a: 'AI assistants (ChatGPT, Perplexity, Gemini)', b: 'Google Maps, local pack, organic results' },
      { label: 'Key ranking signal', a: 'Reviews, citations, AI-readable content', b: 'Google Business Profile, local links, reviews' },
      { label: 'Competition level', a: 'Low — most businesses haven\'t started', b: 'High — most businesses have some optimization' },
      { label: 'Speed to visibility', a: '60–90 days with focused effort', b: '3–6 months minimum for new optimization' },
      { label: 'Early mover advantage', a: 'Significant — get in before AI habits solidify', b: 'Limited — incumbents are already established' },
      { label: 'Cost', a: 'Low cost with big upside if done early', b: 'Moderate to high due to competition' },
    ],
    verdict: 'Local SEO maintains your Google presence. GEO captures the new wave of AI-driven discovery. Businesses that build GEO advantage now will lock in a first-mover position that compounds as AI usage grows.',
    ctaText: 'Start Your AI Visibility Scan',
  },
  {
    slug: 'gemini-vs-chatgpt-for-local-business',
    title: 'Google Gemini vs ChatGPT for Local Business Visibility',
    metaTitle: 'Google Gemini vs ChatGPT: Which Matters More for Local Businesses? | MyGeoRadar',
    metaDescription: 'Google Gemini and ChatGPT both answer local business queries. Here\'s how each one works and what you need to do to appear in both.',
    entityA: 'Google Gemini',
    entityB: 'ChatGPT',
    summary: 'Gemini is deeply tied to Google\'s data ecosystem. ChatGPT draws from broad training data. Both matter for local business visibility in 2026 — but they reward different signals.',
    points: [
      { label: 'Data source', a: 'Google Business Profile, Google Maps, Google Search', b: 'Broad internet training data + optional browsing' },
      { label: 'Best optimization lever', a: 'Google Business Profile + Google reviews', b: 'Third-party mentions, directories, structured content' },
      { label: 'Integration', a: 'Built into Google Search results (AI Overviews)', b: 'Standalone chat interface and API' },
      { label: 'User base', a: 'Google Search users — largest single audience', b: '200M+ active users globally' },
      { label: 'Real-time data', a: 'Yes — live Google data', b: 'Training cutoff + optional live browsing' },
      { label: 'Local intent handling', a: 'Strong — location signals from device and account', b: 'Good — can infer from context' },
    ],
    verdict: 'Gemini is unavoidable because of its Google Search integration. ChatGPT has the broadest user base. A winning GEO strategy optimizes for both: start with Google Business Profile for Gemini, then build broader citations and content for ChatGPT.',
    ctaText: 'Scan Your Visibility on Gemini and ChatGPT',
  },
  {
    slug: 'paid-ads-vs-geo',
    title: 'Paid Ads vs GEO: Where Should Local Businesses Invest?',
    metaTitle: 'Paid Ads vs GEO for Local Businesses: Which Wins Long-Term? | MyGeoRadar',
    metaDescription: 'Google Ads and Facebook Ads deliver quick results but stop working when you stop paying. GEO builds compounding visibility. Here\'s how to decide.',
    entityA: 'GEO',
    entityB: 'Paid Ads',
    summary: 'Paid ads deliver fast, measurable leads but require ongoing spend. GEO is slower to build but compounds over time and doesn\'t stop working when you pause your budget.',
    points: [
      { label: 'Speed to results', a: '60–90 days to measurable improvement', b: 'Immediate — leads from day one' },
      { label: 'Ongoing cost', a: 'Low — improvements persist without ongoing spend', b: 'High — stops delivering when budget stops' },
      { label: 'Compounding returns', a: 'Yes — authority and citations build over time', b: 'No — returns are linear to spend' },
      { label: 'Competition effect', a: 'Competitors can\'t outbid you — AI isn\'t pay-to-play', b: 'Competitors with bigger budgets can outbid you' },
      { label: 'Trust signal', a: 'AI recommendation implies earned authority', b: 'Ad label reduces trust for some users' },
      { label: 'Best use case', a: 'Long-term visibility and authority building', b: 'Immediate lead generation and promotions' },
    ],
    verdict: 'Use both strategically. Run paid ads to generate immediate revenue while building your GEO foundation in parallel. Over time, shift more budget toward GEO as it compounds — reducing your cost per lead and making your business more resilient.',
    ctaText: 'Start Building Your AI Visibility',
  },
  {
    slug: 'claude-vs-chatgpt-for-business-discovery',
    title: 'Claude vs ChatGPT: Which AI Is Better for Business Discovery?',
    metaTitle: 'Claude vs ChatGPT for Business Discovery | MyGeoRadar',
    metaDescription: 'Claude and ChatGPT both answer consumer questions about local businesses. Here\'s how they differ and what each one means for your GEO strategy.',
    entityA: 'Claude',
    entityB: 'ChatGPT',
    summary: 'Claude (by Anthropic) and ChatGPT (by OpenAI) are the two most widely used AI assistants. Both are used for local business recommendations, but they reach different audiences.',
    points: [
      { label: 'Primary audience', a: 'Professionals, researchers, power users', b: 'General consumers, students, businesses' },
      { label: 'Data approach', a: 'Training data with knowledge cutoff', b: 'Training data + optional live browsing' },
      { label: 'Recommendation style', a: 'Detailed, nuanced, cites reasoning', b: 'Direct, fast, conversational' },
      { label: 'Business query volume', a: 'Growing — especially B2B and professional services', b: 'Highest volume for consumer local queries' },
      { label: 'How to optimize', a: 'Strong website content, professional credentials, press', b: 'Reviews, directories, broad citation coverage' },
      { label: 'Market share', a: 'Significant and growing among professionals', b: 'Largest overall consumer user base' },
    ],
    verdict: 'For most local service businesses, ChatGPT visibility should be the top AI priority. But professional service firms — lawyers, financial advisors, consultants — should treat Claude visibility as equally important given its professional user base.',
    ctaText: 'Check Your Visibility on Claude and ChatGPT',
  },
  {
    slug: 'geo-vs-content-marketing',
    title: 'GEO vs Content Marketing: Which Drives More AI Visibility?',
    metaTitle: 'GEO vs Content Marketing for AI Visibility | MyGeoRadar',
    metaDescription: 'Content marketing and GEO both build long-term visibility, but they work differently for AI-driven discovery. Here\'s how to combine them effectively.',
    entityA: 'GEO',
    entityB: 'Content Marketing',
    summary: 'Content marketing builds topical authority over time. GEO directly optimizes the signals AI models use to recommend businesses. Done together, they are the most powerful combination for long-term visibility.',
    points: [
      { label: 'Primary goal', a: 'Get cited in AI-generated answers', b: 'Build topical authority and organic search traffic' },
      { label: 'Key activities', a: 'Citations, reviews, schema, NAP consistency, AI-friendly content', b: 'Blog posts, guides, videos, case studies' },
      { label: 'Time to results', a: '60–90 days with focused effort', b: '6–12 months for meaningful traffic' },
      { label: 'AI impact', a: 'Direct — GEO signals are what AI models measure', b: 'Indirect — good content becomes AI training data over time' },
      { label: 'Maintenance', a: 'Periodic rescans and citation upkeep', b: 'Ongoing content production' },
      { label: 'ROI timeline', a: 'Faster initial returns from targeted fixes', b: 'Higher ceiling over years of consistent effort' },
    ],
    verdict: 'GEO delivers faster wins; content marketing builds a larger long-term moat. Start with GEO fixes for immediate AI visibility gains, then layer in content marketing to compound authority over time. The combination is unbeatable.',
    ctaText: 'Get Your GEO Baseline Score',
  },
  {
    slug: 'google-business-profile-vs-geo',
    title: 'Google Business Profile vs GEO: Are They the Same Thing?',
    metaTitle: 'Google Business Profile vs GEO: What\'s the Difference? | MyGeoRadar',
    metaDescription: 'Google Business Profile is one piece of GEO. Here\'s what GBP does, what it doesn\'t do, and what else you need for complete AI visibility.',
    entityA: 'Full GEO Strategy',
    entityB: 'Google Business Profile Only',
    summary: 'Google Business Profile optimizes your visibility on Google Gemini and Google Maps. A full GEO strategy covers all four major AI platforms — ChatGPT, Perplexity, Gemini, and Claude.',
    points: [
      { label: 'Platforms covered', a: 'ChatGPT, Perplexity, Gemini, Claude', b: 'Google Gemini and Google Maps only' },
      { label: 'Key signals', a: 'Reviews, citations, schema, NAP, content, llms.txt', b: 'GBP completeness, Google reviews, photos' },
      { label: 'Time to set up', a: '2–4 weeks for foundational fixes', b: '1–2 hours to complete your profile' },
      { label: 'Non-Google AI impact', a: 'High — all platforms covered', b: 'Low — ChatGPT and Perplexity not directly affected' },
      { label: 'Competitive advantage', a: 'High — few businesses have done full GEO', b: 'Low — most businesses have GBP set up' },
      { label: 'Ongoing maintenance', a: 'Quarterly scans and citation updates', b: 'Monthly posts and review responses' },
    ],
    verdict: 'Google Business Profile is essential but not sufficient. It handles Gemini and Maps. A complete GEO strategy is needed to capture visibility on ChatGPT and Perplexity — where consumers increasingly go first.',
    ctaText: 'See Your Full AI Visibility Score',
  },
]

export function getComparisonBySlug(slug: string): Comparison | undefined {
  return COMPARISONS.find(c => c.slug === slug)
}
