export interface Industry {
  slug: string
  name: string
  plural: string
  painPoint: string
  aiQuery: string
  avgGeoScore: number
  ctaText: string
  tag: string
}

export const INDUSTRIES: Industry[] = [
  { slug: 'dentists', name: 'Dentist', plural: 'Dentists', painPoint: 'Patients ask AI for dentist recommendations before ever opening Google.', aiQuery: 'best dentist near me', avgGeoScore: 18, ctaText: 'Check Your Dental Practice AI Score', tag: 'Healthcare' },
  { slug: 'lawyers', name: 'Lawyer', plural: 'Lawyers', painPoint: 'Clients search AI for legal help before they search Google — and most law firms are invisible.', aiQuery: 'best personal injury lawyer near me', avgGeoScore: 14, ctaText: 'Check Your Law Firm AI Score', tag: 'Legal' },
  { slug: 'plumbers', name: 'Plumber', plural: 'Plumbers', painPoint: 'Homeowners ask ChatGPT for a plumber before calling anyone. Is your business coming up?', aiQuery: 'best plumber near me', avgGeoScore: 12, ctaText: 'Check Your Plumbing Business AI Score', tag: 'Home Services' },
  { slug: 'roofers', name: 'Roofer', plural: 'Roofers', painPoint: 'Roofing is high-ticket and high-competition. AI answers are where the new leads come from.', aiQuery: 'best roofing company near me', avgGeoScore: 11, ctaText: 'Check Your Roofing Company AI Score', tag: 'Home Services' },
  { slug: 'med-spas', name: 'Med Spa', plural: 'Med Spas', painPoint: "Med spa clients search AI for Botox and filler recommendations. Most med spas don't appear.", aiQuery: 'best med spa near me', avgGeoScore: 16, ctaText: 'Check Your Med Spa AI Score', tag: 'Beauty & Wellness' },
  { slug: 'chiropractors', name: 'Chiropractor', plural: 'Chiropractors', painPoint: 'Pain relief searches are moving to AI. Chiropractors who show up in AI answers get more new patients.', aiQuery: 'best chiropractor near me', avgGeoScore: 15, ctaText: 'Check Your Chiropractic Practice AI Score', tag: 'Healthcare' },
  { slug: 'restaurants', name: 'Restaurant', plural: 'Restaurants', painPoint: "Diners ask ChatGPT where to eat before they open Yelp. Is your restaurant in the answer?", aiQuery: 'best restaurants near me', avgGeoScore: 22, ctaText: 'Check Your Restaurant AI Score', tag: 'Food & Beverage' },
  { slug: 'real-estate-agents', name: 'Real Estate Agent', plural: 'Real Estate Agents', painPoint: 'Home buyers and sellers ask AI for agent recommendations. Most agents are completely invisible.', aiQuery: 'best real estate agent near me', avgGeoScore: 13, ctaText: 'Check Your Real Estate Business AI Score', tag: 'Real Estate' },
  { slug: 'electricians', name: 'Electrician', plural: 'Electricians', painPoint: "Homeowners ask AI for electrician recommendations in an emergency. Who shows up — you or your competitor?", aiQuery: 'best electrician near me', avgGeoScore: 11, ctaText: 'Check Your Electrical Business AI Score', tag: 'Home Services' },
  { slug: 'hvac', name: 'HVAC Company', plural: 'HVAC Companies', painPoint: 'HVAC emergencies happen fast. Homeowners ask AI first. The businesses that show up get the call.', aiQuery: 'best HVAC company near me', avgGeoScore: 12, ctaText: 'Check Your HVAC Business AI Score', tag: 'Home Services' },
  { slug: 'landscapers', name: 'Landscaper', plural: 'Landscapers', painPoint: 'Homeowners ask AI for landscaping quotes before searching Google. Most landscapers are invisible to AI.', aiQuery: 'best landscaper near me', avgGeoScore: 10, ctaText: 'Check Your Landscaping Business AI Score', tag: 'Home Services' },
  { slug: 'accountants', name: 'Accountant', plural: 'Accountants', painPoint: 'Tax and accounting clients ask AI for recommendations. Firms visible to AI win more clients.', aiQuery: 'best accountant near me', avgGeoScore: 15, ctaText: 'Check Your Accounting Firm AI Score', tag: 'Professional Services' },
  { slug: 'financial-advisors', name: 'Financial Advisor', plural: 'Financial Advisors', painPoint: 'People searching for wealth management and retirement planning now start with AI tools.', aiQuery: 'best financial advisor near me', avgGeoScore: 16, ctaText: 'Check Your Financial Practice AI Score', tag: 'Professional Services' },
  { slug: 'insurance-agents', name: 'Insurance Agent', plural: 'Insurance Agents', painPoint: 'Insurance shoppers compare options using AI before ever calling an agent.', aiQuery: 'best insurance agent near me', avgGeoScore: 14, ctaText: 'Check Your Insurance Business AI Score', tag: 'Professional Services' },
  { slug: 'physical-therapists', name: 'Physical Therapist', plural: 'Physical Therapists', painPoint: "Patients recovering from injury ask AI for PT recommendations. Most clinics don't appear.", aiQuery: 'best physical therapist near me', avgGeoScore: 15, ctaText: 'Check Your PT Practice AI Score', tag: 'Healthcare' },
  { slug: 'veterinarians', name: 'Veterinarian', plural: 'Veterinarians', painPoint: "Pet owners ask AI which vet to trust. If your practice isn't visible to AI, you're losing new patients.", aiQuery: 'best vet near me', avgGeoScore: 17, ctaText: 'Check Your Veterinary Practice AI Score', tag: 'Healthcare' },
  { slug: 'optometrists', name: 'Optometrist', plural: 'Optometrists', painPoint: 'Patients ask AI for eye care recommendations. Optometrists visible in AI answers get more appointments.', aiQuery: 'best optometrist near me', avgGeoScore: 15, ctaText: 'Check Your Eye Care Practice AI Score', tag: 'Healthcare' },
  { slug: 'dermatologists', name: 'Dermatologist', plural: 'Dermatologists', painPoint: 'Skin care patients increasingly ask AI assistants for dermatologist recommendations.', aiQuery: 'best dermatologist near me', avgGeoScore: 16, ctaText: 'Check Your Dermatology Practice AI Score', tag: 'Healthcare' },
  { slug: 'gyms', name: 'Gym', plural: 'Gyms', painPoint: "People ask AI to find gyms before they open Google Maps. Your gym needs to be in that answer.", aiQuery: 'best gym near me', avgGeoScore: 20, ctaText: 'Check Your Gym AI Score', tag: 'Fitness' },
  { slug: 'personal-trainers', name: 'Personal Trainer', plural: 'Personal Trainers', painPoint: "Clients searching for a trainer ask AI for recommendations. Most trainers don't show up at all.", aiQuery: 'best personal trainer near me', avgGeoScore: 12, ctaText: 'Check Your Training Business AI Score', tag: 'Fitness' },
  { slug: 'yoga-studios', name: 'Yoga Studio', plural: 'Yoga Studios', painPoint: 'Wellness seekers ask AI which studios to try. Yoga studios with strong GEO get more walk-ins.', aiQuery: 'best yoga studio near me', avgGeoScore: 18, ctaText: 'Check Your Yoga Studio AI Score', tag: 'Fitness' },
  { slug: 'photographers', name: 'Photographer', plural: 'Photographers', painPoint: 'Couples and families ask AI for photographer recommendations. Most photographers are invisible to AI.', aiQuery: 'best photographer near me', avgGeoScore: 13, ctaText: 'Check Your Photography Business AI Score', tag: 'Creative' },
  { slug: 'interior-designers', name: 'Interior Designer', plural: 'Interior Designers', painPoint: 'Homeowners ask AI for interior design recommendations before searching any portfolio site.', aiQuery: 'best interior designer near me', avgGeoScore: 14, ctaText: 'Check Your Design Business AI Score', tag: 'Creative' },
  { slug: 'marketing-agencies', name: 'Marketing Agency', plural: 'Marketing Agencies', painPoint: 'Business owners ask AI which marketing agencies to hire. Agencies not visible to AI lose clients to those who are.', aiQuery: 'best marketing agency near me', avgGeoScore: 17, ctaText: 'Check Your Agency AI Score', tag: 'Professional Services' },
  { slug: 'web-designers', name: 'Web Designer', plural: 'Web Designers', painPoint: 'Businesses ask AI for web design recommendations. Designers visible in AI answers win more projects.', aiQuery: 'best web designer near me', avgGeoScore: 15, ctaText: 'Check Your Web Design Business AI Score', tag: 'Professional Services' },
  { slug: 'cleaning-services', name: 'Cleaning Service', plural: 'Cleaning Services', painPoint: 'Homeowners and offices ask AI for cleaning service recommendations. Most cleaning companies are invisible.', aiQuery: 'best cleaning service near me', avgGeoScore: 13, ctaText: 'Check Your Cleaning Business AI Score', tag: 'Home Services' },
  { slug: 'pest-control', name: 'Pest Control Company', plural: 'Pest Control Companies', painPoint: 'Pest problems are urgent — homeowners ask AI immediately. Companies visible to AI get the call first.', aiQuery: 'best pest control near me', avgGeoScore: 11, ctaText: 'Check Your Pest Control Business AI Score', tag: 'Home Services' },
  { slug: 'car-dealerships', name: 'Car Dealership', plural: 'Car Dealerships', painPoint: 'Car buyers research using AI before visiting any lot. Dealerships visible in AI answers drive more foot traffic.', aiQuery: 'best car dealership near me', avgGeoScore: 19, ctaText: 'Check Your Dealership AI Score', tag: 'Automotive' },
  { slug: 'auto-repair', name: 'Auto Repair Shop', plural: 'Auto Repair Shops', painPoint: 'Car owners ask AI for repair shop recommendations, especially in emergencies.', aiQuery: 'best auto repair shop near me', avgGeoScore: 16, ctaText: 'Check Your Auto Shop AI Score', tag: 'Automotive' },
  { slug: 'hair-salons', name: 'Hair Salon', plural: 'Hair Salons', painPoint: 'New residents and visitors ask AI which hair salons to visit. Most salons have zero AI visibility.', aiQuery: 'best hair salon near me', avgGeoScore: 20, ctaText: 'Check Your Salon AI Score', tag: 'Beauty & Wellness' },
  { slug: 'nail-salons', name: 'Nail Salon', plural: 'Nail Salons', painPoint: 'Nail salon clients ask AI for recommendations before searching Yelp or Google Maps.', aiQuery: 'best nail salon near me', avgGeoScore: 18, ctaText: 'Check Your Nail Salon AI Score', tag: 'Beauty & Wellness' },
  { slug: 'massage-therapists', name: 'Massage Therapist', plural: 'Massage Therapists', painPoint: 'Clients seeking relaxation or pain relief ask AI for massage recommendations first.', aiQuery: 'best massage therapist near me', avgGeoScore: 16, ctaText: 'Check Your Massage Business AI Score', tag: 'Beauty & Wellness' },
  { slug: 'tutors', name: 'Tutor', plural: 'Tutors', painPoint: "Parents ask AI for tutoring recommendations for their children. Most tutors don't show up in AI answers.", aiQuery: 'best tutor near me', avgGeoScore: 12, ctaText: 'Check Your Tutoring Business AI Score', tag: 'Education' },
  { slug: 'daycares', name: 'Daycare', plural: 'Daycares', painPoint: 'Parents searching for childcare ask AI for trusted recommendations. Daycares visible to AI get more inquiries.', aiQuery: 'best daycare near me', avgGeoScore: 14, ctaText: 'Check Your Daycare AI Score', tag: 'Education' },
  { slug: 'contractors', name: 'General Contractor', plural: 'General Contractors', painPoint: "Homeowners planning renovations ask AI which contractors to trust. Most GCs are invisible to AI.", aiQuery: 'best general contractor near me', avgGeoScore: 13, ctaText: 'Check Your Contractor AI Score', tag: 'Home Services' },
  { slug: 'flooring', name: 'Flooring Company', plural: 'Flooring Companies', painPoint: 'Homeowners ask AI for flooring company recommendations before calling anyone.', aiQuery: 'best flooring company near me', avgGeoScore: 11, ctaText: 'Check Your Flooring Business AI Score', tag: 'Home Services' },
  { slug: 'painters', name: 'Painter', plural: 'Painters', painPoint: 'Homeowners ask AI for painter recommendations for interior and exterior projects.', aiQuery: 'best painter near me', avgGeoScore: 11, ctaText: 'Check Your Painting Business AI Score', tag: 'Home Services' },
  { slug: 'mortgage-brokers', name: 'Mortgage Broker', plural: 'Mortgage Brokers', painPoint: 'Home buyers ask AI which mortgage brokers to use. Brokers visible to AI close more loans.', aiQuery: 'best mortgage broker near me', avgGeoScore: 15, ctaText: 'Check Your Mortgage Business AI Score', tag: 'Financial' },
  { slug: 'tax-preparers', name: 'Tax Preparer', plural: 'Tax Preparers', painPoint: "People ask AI for tax prep recommendations every year. Most local preparers don't appear.", aiQuery: 'best tax preparer near me', avgGeoScore: 14, ctaText: 'Check Your Tax Business AI Score', tag: 'Financial' },
  { slug: 'event-planners', name: 'Event Planner', plural: 'Event Planners', painPoint: 'Clients planning weddings and corporate events ask AI for recommendations before searching anywhere else.', aiQuery: 'best event planner near me', avgGeoScore: 15, ctaText: 'Check Your Event Planning Business AI Score', tag: 'Creative' },
  { slug: 'caterers', name: 'Caterer', plural: 'Caterers', painPoint: 'Event hosts ask AI for catering recommendations. Caterers visible to AI get more bookings.', aiQuery: 'best caterer near me', avgGeoScore: 14, ctaText: 'Check Your Catering Business AI Score', tag: 'Food & Beverage' },
  { slug: 'bakeries', name: 'Bakery', plural: 'Bakeries', painPoint: 'Locals and visitors ask AI for bakery recommendations for custom cakes and pastries.', aiQuery: 'best bakery near me', avgGeoScore: 21, ctaText: 'Check Your Bakery AI Score', tag: 'Food & Beverage' },
  { slug: 'coffee-shops', name: 'Coffee Shop', plural: 'Coffee Shops', painPoint: 'Coffee drinkers in new cities ask AI where to go. Independent cafes invisible to AI lose out to chains.', aiQuery: 'best coffee shop near me', avgGeoScore: 24, ctaText: 'Check Your Coffee Shop AI Score', tag: 'Food & Beverage' },
  { slug: 'breweries', name: 'Brewery', plural: 'Breweries', painPoint: 'Craft beer enthusiasts ask AI for brewery recommendations. Breweries with GEO get more taproom visits.', aiQuery: 'best brewery near me', avgGeoScore: 22, ctaText: 'Check Your Brewery AI Score', tag: 'Food & Beverage' },
  { slug: 'therapists', name: 'Therapist', plural: 'Therapists', painPoint: 'People seeking mental health support ask AI for therapist recommendations with specific criteria.', aiQuery: 'best therapist near me', avgGeoScore: 14, ctaText: 'Check Your Therapy Practice AI Score', tag: 'Healthcare' },
  { slug: 'urgent-care', name: 'Urgent Care Clinic', plural: 'Urgent Care Clinics', painPoint: 'Patients in non-emergency situations ask AI which urgent care clinic to visit.', aiQuery: 'best urgent care near me', avgGeoScore: 19, ctaText: 'Check Your Urgent Care AI Score', tag: 'Healthcare' },
  { slug: 'hotels', name: 'Hotel', plural: 'Hotels', painPoint: "Travelers ask AI for hotel recommendations before ever opening Booking.com or Expedia.", aiQuery: 'best hotel near me', avgGeoScore: 26, ctaText: 'Check Your Hotel AI Score', tag: 'Hospitality' },
  { slug: 'wedding-venues', name: 'Wedding Venue', plural: 'Wedding Venues', painPoint: 'Couples ask AI for wedding venue recommendations early in their planning journey.', aiQuery: 'best wedding venues near me', avgGeoScore: 17, ctaText: 'Check Your Venue AI Score', tag: 'Hospitality' },
  { slug: 'moving-companies', name: 'Moving Company', plural: 'Moving Companies', painPoint: 'People moving homes ask AI for trusted moving company recommendations before reading reviews.', aiQuery: 'best moving company near me', avgGeoScore: 13, ctaText: 'Check Your Moving Business AI Score', tag: 'Home Services' },
  { slug: 'storage-facilities', name: 'Storage Facility', plural: 'Storage Facilities', painPoint: 'People downsizing or moving ask AI for storage facility recommendations in their area.', aiQuery: 'best storage facility near me', avgGeoScore: 18, ctaText: 'Check Your Storage Business AI Score', tag: 'Home Services' },
  // --- Expanded: 25 additional industries ---
  { slug: 'dog-groomers', name: 'Dog Groomer', plural: 'Dog Groomers', painPoint: 'Pet owners ask AI which dog groomers to trust for their furry family members.', aiQuery: 'best dog groomer near me', avgGeoScore: 15, ctaText: 'Check Your Grooming Business AI Score', tag: 'Pet Services' },
  { slug: 'dog-trainers', name: 'Dog Trainer', plural: 'Dog Trainers', painPoint: 'Dog owners ask AI for trainer recommendations before searching anywhere else.', aiQuery: 'best dog trainer near me', avgGeoScore: 13, ctaText: 'Check Your Dog Training Business AI Score', tag: 'Pet Services' },
  { slug: 'pet-boarding', name: 'Pet Boarding Facility', plural: 'Pet Boarding Facilities', painPoint: 'Pet owners traveling ask AI which boarding facilities to trust with their animals.', aiQuery: 'best pet boarding near me', avgGeoScore: 16, ctaText: 'Check Your Pet Boarding AI Score', tag: 'Pet Services' },
  { slug: 'it-support', name: 'IT Support Company', plural: 'IT Support Companies', painPoint: 'Small businesses ask AI for IT support recommendations when things break down.', aiQuery: 'best IT support company near me', avgGeoScore: 14, ctaText: 'Check Your IT Business AI Score', tag: 'Technology' },
  { slug: 'cybersecurity-firms', name: 'Cybersecurity Firm', plural: 'Cybersecurity Firms', painPoint: 'Business owners ask AI which cybersecurity firms to trust with their data protection.', aiQuery: 'best cybersecurity company near me', avgGeoScore: 12, ctaText: 'Check Your Cybersecurity Business AI Score', tag: 'Technology' },
  { slug: 'pool-service', name: 'Pool Service Company', plural: 'Pool Service Companies', painPoint: 'Pool owners ask AI for maintenance and repair recommendations before calling anyone.', aiQuery: 'best pool service company near me', avgGeoScore: 11, ctaText: 'Check Your Pool Business AI Score', tag: 'Home Services' },
  { slug: 'window-cleaners', name: 'Window Cleaning Company', plural: 'Window Cleaning Companies', painPoint: 'Homeowners and property managers ask AI for window cleaning recommendations.', aiQuery: 'best window cleaning near me', avgGeoScore: 10, ctaText: 'Check Your Window Cleaning AI Score', tag: 'Home Services' },
  { slug: 'speech-therapists', name: 'Speech Therapist', plural: 'Speech Therapists', painPoint: 'Parents of children with speech delays ask AI for trusted speech therapy recommendations.', aiQuery: 'best speech therapist near me', avgGeoScore: 14, ctaText: 'Check Your Speech Therapy Practice AI Score', tag: 'Healthcare' },
  { slug: 'acupuncturists', name: 'Acupuncturist', plural: 'Acupuncturists', painPoint: 'Patients seeking alternative medicine ask AI for acupuncturist recommendations.', aiQuery: 'best acupuncturist near me', avgGeoScore: 14, ctaText: 'Check Your Acupuncture Practice AI Score', tag: 'Healthcare' },
  { slug: 'pediatricians', name: 'Pediatrician', plural: 'Pediatricians', painPoint: 'New parents ask AI which pediatricians come most recommended in their area.', aiQuery: 'best pediatrician near me', avgGeoScore: 16, ctaText: 'Check Your Pediatric Practice AI Score', tag: 'Healthcare' },
  { slug: 'divorce-lawyers', name: 'Divorce Lawyer', plural: 'Divorce Lawyers', painPoint: 'People going through a divorce ask AI for trusted legal recommendations discretely.', aiQuery: 'best divorce lawyer near me', avgGeoScore: 13, ctaText: 'Check Your Family Law Firm AI Score', tag: 'Legal' },
  { slug: 'immigration-lawyers', name: 'Immigration Lawyer', plural: 'Immigration Lawyers', painPoint: 'Immigrants and visa applicants ask AI for immigration attorney recommendations.', aiQuery: 'best immigration lawyer near me', avgGeoScore: 13, ctaText: 'Check Your Immigration Law Firm AI Score', tag: 'Legal' },
  { slug: 'bookkeepers', name: 'Bookkeeper', plural: 'Bookkeepers', painPoint: 'Small business owners ask AI for bookkeeping recommendations to manage their finances.', aiQuery: 'best bookkeeper near me', avgGeoScore: 13, ctaText: 'Check Your Bookkeeping Business AI Score', tag: 'Financial' },
  { slug: 'credit-repair', name: 'Credit Repair Company', plural: 'Credit Repair Companies', painPoint: 'People with credit challenges ask AI which companies to trust for credit repair.', aiQuery: 'best credit repair company near me', avgGeoScore: 12, ctaText: 'Check Your Credit Repair Business AI Score', tag: 'Financial' },
  { slug: 'pilates-studios', name: 'Pilates Studio', plural: 'Pilates Studios', painPoint: 'Fitness enthusiasts ask AI for Pilates studio recommendations before trying anything new.', aiQuery: 'best pilates studio near me', avgGeoScore: 17, ctaText: 'Check Your Pilates Studio AI Score', tag: 'Fitness' },
  { slug: 'martial-arts', name: 'Martial Arts School', plural: 'Martial Arts Schools', painPoint: 'Parents and adults ask AI for martial arts school recommendations for their family.', aiQuery: 'best martial arts school near me', avgGeoScore: 16, ctaText: 'Check Your Martial Arts School AI Score', tag: 'Fitness' },
  { slug: 'tattoo-shops', name: 'Tattoo Shop', plural: 'Tattoo Shops', painPoint: 'People planning their first or next tattoo ask AI which shops have the best artists.', aiQuery: 'best tattoo shop near me', avgGeoScore: 19, ctaText: 'Check Your Tattoo Shop AI Score', tag: 'Beauty & Wellness' },
  { slug: 'barbers', name: 'Barber Shop', plural: 'Barber Shops', painPoint: 'Men in new cities ask AI which barbers to visit. Shops visible to AI get the walk-ins.', aiQuery: 'best barber near me', avgGeoScore: 21, ctaText: 'Check Your Barber Shop AI Score', tag: 'Beauty & Wellness' },
  { slug: 'music-schools', name: 'Music School', plural: 'Music Schools', painPoint: 'Parents looking for music lessons for their children ask AI for school recommendations.', aiQuery: 'best music school near me', avgGeoScore: 14, ctaText: 'Check Your Music School AI Score', tag: 'Education' },
  { slug: 'driving-schools', name: 'Driving School', plural: 'Driving Schools', painPoint: 'Teens and adults learning to drive ask AI which driving schools are most trusted.', aiQuery: 'best driving school near me', avgGeoScore: 15, ctaText: 'Check Your Driving School AI Score', tag: 'Education' },
  { slug: 'wineries', name: 'Winery', plural: 'Wineries', painPoint: 'Wine enthusiasts ask AI for winery recommendations for tastings and events.', aiQuery: 'best winery near me', avgGeoScore: 21, ctaText: 'Check Your Winery AI Score', tag: 'Food & Beverage' },
  { slug: 'food-trucks', name: 'Food Truck', plural: 'Food Trucks', painPoint: 'Foodies and event planners ask AI which food trucks to hire or visit.', aiQuery: 'best food truck near me', avgGeoScore: 17, ctaText: 'Check Your Food Truck AI Score', tag: 'Food & Beverage' },
  { slug: 'vacation-rentals', name: 'Vacation Rental', plural: 'Vacation Rentals', painPoint: 'Travelers ask AI for vacation rental recommendations as an alternative to hotels.', aiQuery: 'best vacation rentals near me', avgGeoScore: 20, ctaText: 'Check Your Vacation Rental AI Score', tag: 'Hospitality' },
  { slug: 'auto-detailing', name: 'Auto Detailing Shop', plural: 'Auto Detailing Shops', painPoint: 'Car owners ask AI for detailing shop recommendations before booking online.', aiQuery: 'best auto detailing near me', avgGeoScore: 15, ctaText: 'Check Your Auto Detailing AI Score', tag: 'Automotive' },
  { slug: 'tire-shops', name: 'Tire Shop', plural: 'Tire Shops', painPoint: 'Drivers needing new tires ask AI for recommendations before visiting any shop.', aiQuery: 'best tire shop near me', avgGeoScore: 14, ctaText: 'Check Your Tire Shop AI Score', tag: 'Automotive' },
]

export function getIndustryBySlug(slug: string): Industry | undefined {
  return INDUSTRIES.find(i => i.slug === slug)
}

export const INDUSTRY_TAGS = Array.from(new Set(INDUSTRIES.map(i => i.tag)))
