// Programmatic SEO data — industries × cities
// Each combination generates a unique landing page at /[industry]/[city]
// 34 industries × 100 cities = 3,400 programmatic pages

export type Industry = {
  slug: string
  label: string
  plural: string
  emoji: string
  painPhrase: string
  topProblem: string
  aiExample: string
}

export type City = {
  slug: string
  label: string
  state: string
  stateAbbr: string
  population: string
  metro: string
}

export const INDUSTRIES: Industry[] = [
  {
    slug: 'dentists',
    label: 'Dentist',
    plural: 'Dentists',
    emoji: '🦷',
    painPhrase: 'most patients search on Google or ask ChatGPT before calling',
    topProblem: 'incomplete Google Business Profile and missing LocalBusiness schema',
    aiExample: 'ChatGPT recommends dentists by name — but only if your online citations are consistent',
  },
  {
    slug: 'plumbers',
    label: 'Plumber',
    plural: 'Plumbers',
    emoji: '🔧',
    painPhrase: "emergency plumber searches happen in seconds — you either show up or you don't",
    topProblem: 'missing or inconsistent NAP data across directories',
    aiExample: 'Perplexity and Google AI Overviews pull from citation data — outdated listings mean invisible rankings',
  },
  {
    slug: 'lawyers',
    label: 'Lawyer',
    plural: 'Lawyers',
    emoji: '⚖️',
    painPhrase: 'people searching for an attorney use Google, AI chat, and review sites before calling',
    topProblem: 'weak or absent schema markup and thin Google Business Profile',
    aiExample: 'AI systems recommend attorneys from authoritative, well-structured profiles — not just review count',
  },
  {
    slug: 'restaurants',
    label: 'Restaurant',
    plural: 'Restaurants',
    emoji: '🍽️',
    painPhrase: 'diners ask Google and AI assistants where to eat — before they ever open Yelp',
    topProblem: 'outdated hours, missing menu schema, and citation inconsistencies across delivery platforms',
    aiExample: 'ChatGPT and Gemini recommend restaurants by name when structured data and citations are clean',
  },
  {
    slug: 'med-spas',
    label: 'Med Spa',
    plural: 'Med Spas',
    emoji: '💆',
    painPhrase: 'med spa clients research heavily before booking — across Google, AI, and Instagram',
    topProblem: 'no LocalBusiness or MedicalBusiness schema and weak citation presence',
    aiExample: 'AI assistants surface med spas with complete, trustworthy structured data — not just star ratings',
  },
  {
    slug: 'chiropractors',
    label: 'Chiropractor',
    plural: 'Chiropractors',
    emoji: '🩺',
    painPhrase: 'patients in pain search fast — your GBP and schema determine if they find you first',
    topProblem: 'incomplete GBP categories and missing HealthAndBeautyBusiness schema',
    aiExample: 'Perplexity surfaces chiropractors with complete authority signals — not just proximity',
  },
  {
    slug: 'contractors',
    label: 'Contractor',
    plural: 'Contractors',
    emoji: '🏗️',
    painPhrase: 'homeowners search for contractors online — and AI is now the first stop',
    topProblem: 'missing service area pages, inconsistent NAP, and no HomeAndConstructionBusiness schema',
    aiExample: 'AI tools recommend contractors from trusted, structured, consistently cited sources',
  },
  {
    slug: 'real-estate-agents',
    label: 'Real Estate Agent',
    plural: 'Real Estate Agents',
    emoji: '🏠',
    painPhrase: 'buyers and sellers research agents across Google, Zillow, and AI before reaching out',
    topProblem: 'thin Google Business Profile and missing RealEstateAgent schema',
    aiExample: 'AI assistants cite real estate agents from platforms with rich, consistent structured data',
  },
  {
    slug: 'electricians',
    label: 'Electrician',
    plural: 'Electricians',
    emoji: '⚡',
    painPhrase: 'homeowners ask AI for electrician recommendations in an emergency — speed matters',
    topProblem: 'no service area schema and inconsistent NAP across directories',
    aiExample: 'AI tools recommend electricians from well-structured, citation-rich local profiles',
  },
  {
    slug: 'hvac',
    label: 'HVAC Company',
    plural: 'HVAC Companies',
    emoji: '❄️',
    painPhrase: 'HVAC emergencies happen fast — homeowners ask AI first and call whoever shows up',
    topProblem: 'missing HomeAndConstructionBusiness schema and thin GBP',
    aiExample: 'The businesses that show up in AI answers for HVAC get the emergency call',
  },
  {
    slug: 'landscapers',
    label: 'Landscaper',
    plural: 'Landscapers',
    emoji: '🌿',
    painPhrase: 'homeowners ask AI for landscaping quotes before searching Google',
    topProblem: 'missing service area pages and weak citation presence',
    aiExample: 'AI surfaces landscapers with complete GBP and consistent citations across local directories',
  },
  {
    slug: 'accountants',
    label: 'Accountant',
    plural: 'Accountants',
    emoji: '📊',
    painPhrase: 'tax and accounting clients ask AI for recommendations before calling any firm',
    topProblem: 'thin Google Business Profile and missing ProfessionalService schema',
    aiExample: 'AI recommends accountants from firms with complete authority signals and clean citations',
  },
  {
    slug: 'financial-advisors',
    label: 'Financial Advisor',
    plural: 'Financial Advisors',
    emoji: '💰',
    painPhrase: 'people searching for wealth management now start with AI tools before calling',
    topProblem: 'missing FinancialService schema and low citation authority',
    aiExample: 'AI assistants surface financial advisors from profiles with high trust signals and schema',
  },
  {
    slug: 'insurance-agents',
    label: 'Insurance Agent',
    plural: 'Insurance Agents',
    emoji: '🛡️',
    painPhrase: 'insurance shoppers compare options using AI before ever calling an agent',
    topProblem: 'no InsuranceAgency schema and inconsistent business listings',
    aiExample: 'AI recommends insurance agents whose profiles are complete, cited, and schema-rich',
  },
  {
    slug: 'physical-therapists',
    label: 'Physical Therapist',
    plural: 'Physical Therapists',
    emoji: '🏋️',
    painPhrase: 'patients recovering from injury ask AI for PT recommendations before calling clinics',
    topProblem: 'missing MedicalBusiness schema and incomplete GBP',
    aiExample: 'AI surfaces PT clinics from profiles with complete health-category schema and clean citations',
  },
  {
    slug: 'veterinarians',
    label: 'Veterinarian',
    plural: 'Veterinarians',
    emoji: '🐾',
    painPhrase: 'pet owners ask AI which vet to trust before booking any appointment',
    topProblem: 'incomplete VeterinaryCare schema and weak citation profile',
    aiExample: 'AI tools recommend veterinarians from practices with complete structured data and directory presence',
  },
  {
    slug: 'optometrists',
    label: 'Optometrist',
    plural: 'Optometrists',
    emoji: '👁️',
    painPhrase: 'patients ask AI for eye care recommendations before searching any map',
    topProblem: 'missing Optician schema and thin GBP service details',
    aiExample: 'AI recommends optometrists from practices with verified, schema-enriched local profiles',
  },
  {
    slug: 'dermatologists',
    label: 'Dermatologist',
    plural: 'Dermatologists',
    emoji: '🧴',
    painPhrase: 'skin care patients increasingly ask AI assistants for dermatologist recommendations',
    topProblem: 'no Dermatology schema and low authority citations',
    aiExample: 'AI surfaces dermatologists from practices with complete medical-category structured data',
  },
  {
    slug: 'gyms',
    label: 'Gym',
    plural: 'Gyms',
    emoji: '💪',
    painPhrase: 'people ask AI to find gyms before they open Google Maps',
    topProblem: 'missing SportsActivityLocation schema and inconsistent GBP hours',
    aiExample: 'AI recommends gyms with complete hours, categories, and citation consistency',
  },
  {
    slug: 'personal-trainers',
    label: 'Personal Trainer',
    plural: 'Personal Trainers',
    emoji: '🏃',
    painPhrase: 'clients searching for a trainer ask AI for recommendations before browsing Instagram',
    topProblem: 'no structured business profile and missing ExerciseGym schema',
    aiExample: 'AI tools surface personal trainers from profiles with verified location and category data',
  },
  {
    slug: 'yoga-studios',
    label: 'Yoga Studio',
    plural: 'Yoga Studios',
    emoji: '🧘',
    painPhrase: 'wellness seekers ask AI which studios to try before visiting any website',
    topProblem: 'incomplete SportsActivityLocation schema and missing GBP amenities',
    aiExample: 'AI recommends yoga studios from listings with clean citations and complete structured data',
  },
  {
    slug: 'photographers',
    label: 'Photographer',
    plural: 'Photographers',
    emoji: '📸',
    painPhrase: 'couples and families ask AI for photographer recommendations before searching portfolios',
    topProblem: 'no LocalBusiness or ProfessionalService schema and weak directory presence',
    aiExample: 'AI surfaces photographers from profiles with verified location, category, and citation data',
  },
  {
    slug: 'interior-designers',
    label: 'Interior Designer',
    plural: 'Interior Designers',
    emoji: '🛋️',
    painPhrase: 'homeowners ask AI for interior design recommendations before visiting any portfolio',
    topProblem: 'missing ProfessionalService schema and thin GBP photo gallery',
    aiExample: 'AI recommends interior designers from profiles with complete authority and citation signals',
  },
  {
    slug: 'marketing-agencies',
    label: 'Marketing Agency',
    plural: 'Marketing Agencies',
    emoji: '📣',
    painPhrase: 'business owners ask AI which marketing agencies to hire — before requesting any proposal',
    topProblem: 'no ProfessionalService schema and inconsistent NAP across agency directories',
    aiExample: 'AI surfaces agencies with strong authority signals, clean citations, and rich structured data',
  },
  {
    slug: 'web-designers',
    label: 'Web Designer',
    plural: 'Web Designers',
    emoji: '🖥️',
    painPhrase: 'businesses ask AI for web design recommendations before browsing any portfolio',
    topProblem: 'thin GBP and missing ProfessionalService or ITService schema',
    aiExample: 'AI recommends web designers from profiles with verified location and consistent citations',
  },
  {
    slug: 'cleaning-services',
    label: 'Cleaning Service',
    plural: 'Cleaning Services',
    emoji: '🧹',
    painPhrase: 'homeowners and offices ask AI for cleaning service recommendations before searching Yelp',
    topProblem: 'missing HomeAndConstructionBusiness schema and inconsistent citation data',
    aiExample: 'AI tools surface cleaning services from consistently cited, schema-complete local profiles',
  },
  {
    slug: 'pest-control',
    label: 'Pest Control Company',
    plural: 'Pest Control Companies',
    emoji: '🐛',
    painPhrase: 'pest problems are urgent — homeowners ask AI immediately and call whoever shows up first',
    topProblem: 'no LocalBusiness schema and sparse directory citations',
    aiExample: 'AI recommends pest control companies visible across authoritative local citation sources',
  },
  {
    slug: 'car-dealerships',
    label: 'Car Dealership',
    plural: 'Car Dealerships',
    emoji: '🚗',
    painPhrase: 'car buyers research using AI before visiting any lot — visibility in AI answers drives foot traffic',
    topProblem: 'missing AutoDealer schema and incomplete GBP inventory signals',
    aiExample: 'AI recommends dealerships from profiles with rich schema, verified location, and consistent listings',
  },
  {
    slug: 'auto-repair',
    label: 'Auto Repair Shop',
    plural: 'Auto Repair Shops',
    emoji: '🔩',
    painPhrase: 'car owners ask AI for repair shop recommendations especially in emergencies',
    topProblem: 'no AutomotiveBusiness schema and inconsistent NAP across directories',
    aiExample: 'AI surfaces auto repair shops from profiles with complete category schema and strong citations',
  },
  {
    slug: 'hair-salons',
    label: 'Hair Salon',
    plural: 'Hair Salons',
    emoji: '✂️',
    painPhrase: 'new residents and visitors ask AI which hair salons to visit before opening any app',
    topProblem: 'missing HairSalon schema and inconsistent business name across booking platforms',
    aiExample: 'AI recommends hair salons from profiles with complete structured data and strong citation presence',
  },
  {
    slug: 'nail-salons',
    label: 'Nail Salon',
    plural: 'Nail Salons',
    emoji: '💅',
    painPhrase: 'nail salon clients ask AI for recommendations before searching Yelp or Google Maps',
    topProblem: 'weak GBP photo content and missing NailSalon schema',
    aiExample: 'AI surfaces nail salons from consistently cited, schema-rich local business profiles',
  },
  {
    slug: 'massage-therapists',
    label: 'Massage Therapist',
    plural: 'Massage Therapists',
    emoji: '💆',
    painPhrase: 'clients seeking relaxation or pain relief ask AI for massage recommendations first',
    topProblem: 'missing HealthAndBeautyBusiness schema and thin citation presence',
    aiExample: 'AI recommends massage therapists from profiles with verified location and complete service schema',
  },
  {
    slug: 'tutors',
    label: 'Tutor',
    plural: 'Tutors',
    emoji: '📚',
    painPhrase: 'parents ask AI for tutoring recommendations for their children before contacting anyone',
    topProblem: 'no EducationalOrganization schema and missing GBP service categories',
    aiExample: 'AI surfaces tutors from profiles with complete education-category schema and strong local citations',
  },
]

export const CITIES: City[] = [
  { slug: 'new-york', label: 'New York', state: 'New York', stateAbbr: 'NY', population: '8.3M', metro: 'New York metro' },
  { slug: 'los-angeles', label: 'Los Angeles', state: 'California', stateAbbr: 'CA', population: '3.9M', metro: 'LA metro' },
  { slug: 'chicago', label: 'Chicago', state: 'Illinois', stateAbbr: 'IL', population: '2.7M', metro: 'Chicagoland' },
  { slug: 'houston', label: 'Houston', state: 'Texas', stateAbbr: 'TX', population: '2.3M', metro: 'Greater Houston' },
  { slug: 'phoenix', label: 'Phoenix', state: 'Arizona', stateAbbr: 'AZ', population: '1.6M', metro: 'Phoenix metro' },
  { slug: 'philadelphia', label: 'Philadelphia', state: 'Pennsylvania', stateAbbr: 'PA', population: '1.6M', metro: 'Greater Philadelphia' },
  { slug: 'san-antonio', label: 'San Antonio', state: 'Texas', stateAbbr: 'TX', population: '1.4M', metro: 'San Antonio metro' },
  { slug: 'san-diego', label: 'San Diego', state: 'California', stateAbbr: 'CA', population: '1.4M', metro: 'San Diego metro' },
  { slug: 'dallas', label: 'Dallas', state: 'Texas', stateAbbr: 'TX', population: '1.3M', metro: 'DFW metro' },
  { slug: 'miami', label: 'Miami', state: 'Florida', stateAbbr: 'FL', population: '468K', metro: 'South Florida' },
  { slug: 'austin', label: 'Austin', state: 'Texas', stateAbbr: 'TX', population: '978K', metro: 'Greater Austin' },
  { slug: 'seattle', label: 'Seattle', state: 'Washington', stateAbbr: 'WA', population: '749K', metro: 'Puget Sound' },
  { slug: 'denver', label: 'Denver', state: 'Colorado', stateAbbr: 'CO', population: '715K', metro: 'Denver metro' },
  { slug: 'boston', label: 'Boston', state: 'Massachusetts', stateAbbr: 'MA', population: '675K', metro: 'Greater Boston' },
  { slug: 'atlanta', label: 'Atlanta', state: 'Georgia', stateAbbr: 'GA', population: '498K', metro: 'Metro Atlanta' },
  { slug: 'nashville', label: 'Nashville', state: 'Tennessee', stateAbbr: 'TN', population: '689K', metro: 'Nashville metro' },
  { slug: 'portland', label: 'Portland', state: 'Oregon', stateAbbr: 'OR', population: '652K', metro: 'Portland metro' },
  { slug: 'las-vegas', label: 'Las Vegas', state: 'Nevada', stateAbbr: 'NV', population: '641K', metro: 'Las Vegas metro' },
  { slug: 'charlotte', label: 'Charlotte', state: 'North Carolina', stateAbbr: 'NC', population: '874K', metro: 'Charlotte metro' },
  { slug: 'minneapolis', label: 'Minneapolis', state: 'Minnesota', stateAbbr: 'MN', population: '429K', metro: 'Twin Cities' },
  { slug: 'san-jose', label: 'San Jose', state: 'California', stateAbbr: 'CA', population: '1.0M', metro: 'Silicon Valley' },
  { slug: 'jacksonville', label: 'Jacksonville', state: 'Florida', stateAbbr: 'FL', population: '950K', metro: 'Jacksonville metro' },
  { slug: 'fort-worth', label: 'Fort Worth', state: 'Texas', stateAbbr: 'TX', population: '919K', metro: 'DFW metro' },
  { slug: 'columbus', label: 'Columbus', state: 'Ohio', stateAbbr: 'OH', population: '906K', metro: 'Columbus metro' },
  { slug: 'indianapolis', label: 'Indianapolis', state: 'Indiana', stateAbbr: 'IN', population: '888K', metro: 'Indianapolis metro' },
  { slug: 'san-francisco', label: 'San Francisco', state: 'California', stateAbbr: 'CA', population: '882K', metro: 'Bay Area' },
  { slug: 'baltimore', label: 'Baltimore', state: 'Maryland', stateAbbr: 'MD', population: '586K', metro: 'Baltimore metro' },
  { slug: 'milwaukee', label: 'Milwaukee', state: 'Wisconsin', stateAbbr: 'WI', population: '577K', metro: 'Milwaukee metro' },
  { slug: 'albuquerque', label: 'Albuquerque', state: 'New Mexico', stateAbbr: 'NM', population: '565K', metro: 'Albuquerque metro' },
  { slug: 'tucson', label: 'Tucson', state: 'Arizona', stateAbbr: 'AZ', population: '543K', metro: 'Tucson metro' },
  { slug: 'fresno', label: 'Fresno', state: 'California', stateAbbr: 'CA', population: '530K', metro: 'Fresno metro' },
  { slug: 'mesa', label: 'Mesa', state: 'Arizona', stateAbbr: 'AZ', population: '504K', metro: 'Phoenix metro' },
  { slug: 'sacramento', label: 'Sacramento', state: 'California', stateAbbr: 'CA', population: '514K', metro: 'Sacramento metro' },
  { slug: 'kansas-city', label: 'Kansas City', state: 'Missouri', stateAbbr: 'MO', population: '508K', metro: 'KC metro' },
  { slug: 'long-beach', label: 'Long Beach', state: 'California', stateAbbr: 'CA', population: '467K', metro: 'LA metro' },
  { slug: 'raleigh', label: 'Raleigh', state: 'North Carolina', stateAbbr: 'NC', population: '468K', metro: 'Research Triangle' },
  { slug: 'omaha', label: 'Omaha', state: 'Nebraska', stateAbbr: 'NE', population: '486K', metro: 'Omaha metro' },
  { slug: 'colorado-springs', label: 'Colorado Springs', state: 'Colorado', stateAbbr: 'CO', population: '473K', metro: 'Colorado Springs metro' },
  { slug: 'tampa', label: 'Tampa', state: 'Florida', stateAbbr: 'FL', population: '400K', metro: 'Tampa Bay' },
  { slug: 'new-orleans', label: 'New Orleans', state: 'Louisiana', stateAbbr: 'LA', population: '391K', metro: 'Greater New Orleans' },
  { slug: 'cleveland', label: 'Cleveland', state: 'Ohio', stateAbbr: 'OH', population: '373K', metro: 'Cleveland metro' },
  { slug: 'pittsburgh', label: 'Pittsburgh', state: 'Pennsylvania', stateAbbr: 'PA', population: '303K', metro: 'Pittsburgh metro' },
  { slug: 'orlando', label: 'Orlando', state: 'Florida', stateAbbr: 'FL', population: '308K', metro: 'Orlando metro' },
  { slug: 'st-louis', label: 'St. Louis', state: 'Missouri', stateAbbr: 'MO', population: '302K', metro: 'Greater St. Louis' },
  { slug: 'richmond', label: 'Richmond', state: 'Virginia', stateAbbr: 'VA', population: '227K', metro: 'Richmond metro' },
  { slug: 'salt-lake-city', label: 'Salt Lake City', state: 'Utah', stateAbbr: 'UT', population: '200K', metro: 'Salt Lake metro' },
  { slug: 'birmingham', label: 'Birmingham', state: 'Alabama', stateAbbr: 'AL', population: '212K', metro: 'Birmingham metro' },
  { slug: 'hartford', label: 'Hartford', state: 'Connecticut', stateAbbr: 'CT', population: '121K', metro: 'Greater Hartford' },
  { slug: 'virginia-beach', label: 'Virginia Beach', state: 'Virginia', stateAbbr: 'VA', population: '459K', metro: 'Hampton Roads' },
  { slug: 'el-paso', label: 'El Paso', state: 'Texas', stateAbbr: 'TX', population: '679K', metro: 'El Paso metro' },
  { slug: 'oklahoma-city', label: 'Oklahoma City', state: 'Oklahoma', stateAbbr: 'OK', population: '649K', metro: 'OKC metro' },
  { slug: 'detroit', label: 'Detroit', state: 'Michigan', stateAbbr: 'MI', population: '673K', metro: 'Metro Detroit' },
  { slug: 'aurora', label: 'Aurora', state: 'Colorado', stateAbbr: 'CO', population: '367K', metro: 'Denver metro' },
  { slug: 'corpus-christi', label: 'Corpus Christi', state: 'Texas', stateAbbr: 'TX', population: '327K', metro: 'Corpus Christi metro' },
  { slug: 'riverside', label: 'Riverside', state: 'California', stateAbbr: 'CA', population: '315K', metro: 'Inland Empire' },
  { slug: 'lexington', label: 'Lexington', state: 'Kentucky', stateAbbr: 'KY', population: '324K', metro: 'Lexington metro' },
  { slug: 'henderson', label: 'Henderson', state: 'Nevada', stateAbbr: 'NV', population: '320K', metro: 'Las Vegas metro' },
  { slug: 'stockton', label: 'Stockton', state: 'California', stateAbbr: 'CA', population: '313K', metro: 'Stockton metro' },
  { slug: 'st-paul', label: 'St. Paul', state: 'Minnesota', stateAbbr: 'MN', population: '308K', metro: 'Twin Cities' },
  { slug: 'anchorage', label: 'Anchorage', state: 'Alaska', stateAbbr: 'AK', population: '292K', metro: 'Anchorage metro' },
  { slug: 'plano', label: 'Plano', state: 'Texas', stateAbbr: 'TX', population: '288K', metro: 'DFW metro' },
  { slug: 'newark', label: 'Newark', state: 'New Jersey', stateAbbr: 'NJ', population: '283K', metro: 'NYC metro' },
  { slug: 'greensboro', label: 'Greensboro', state: 'North Carolina', stateAbbr: 'NC', population: '299K', metro: 'Piedmont Triad' },
  { slug: 'buffalo', label: 'Buffalo', state: 'New York', stateAbbr: 'NY', population: '255K', metro: 'Buffalo metro' },
  { slug: 'lincoln', label: 'Lincoln', state: 'Nebraska', stateAbbr: 'NE', population: '289K', metro: 'Lincoln metro' },
  { slug: 'durham', label: 'Durham', state: 'North Carolina', stateAbbr: 'NC', population: '279K', metro: 'Research Triangle' },
  { slug: 'chandler', label: 'Chandler', state: 'Arizona', stateAbbr: 'AZ', population: '261K', metro: 'Phoenix metro' },
  { slug: 'fort-wayne', label: 'Fort Wayne', state: 'Indiana', stateAbbr: 'IN', population: '264K', metro: 'Fort Wayne metro' },
  { slug: 'jersey-city', label: 'Jersey City', state: 'New Jersey', stateAbbr: 'NJ', population: '262K', metro: 'NYC metro' },
  { slug: 'st-petersburg', label: 'St. Petersburg', state: 'Florida', stateAbbr: 'FL', population: '258K', metro: 'Tampa Bay' },
  { slug: 'laredo', label: 'Laredo', state: 'Texas', stateAbbr: 'TX', population: '255K', metro: 'Laredo metro' },
  { slug: 'norfolk', label: 'Norfolk', state: 'Virginia', stateAbbr: 'VA', population: '245K', metro: 'Hampton Roads' },
  { slug: 'madison', label: 'Madison', state: 'Wisconsin', stateAbbr: 'WI', population: '270K', metro: 'Madison metro' },
  { slug: 'lubbock', label: 'Lubbock', state: 'Texas', stateAbbr: 'TX', population: '259K', metro: 'Lubbock metro' },
  { slug: 'winston-salem', label: 'Winston-Salem', state: 'North Carolina', stateAbbr: 'NC', population: '250K', metro: 'Piedmont Triad' },
  { slug: 'garland', label: 'Garland', state: 'Texas', stateAbbr: 'TX', population: '235K', metro: 'DFW metro' },
  { slug: 'baton-rouge', label: 'Baton Rouge', state: 'Louisiana', stateAbbr: 'LA', population: '227K', metro: 'Baton Rouge metro' },
  { slug: 'scottsdale', label: 'Scottsdale', state: 'Arizona', stateAbbr: 'AZ', population: '258K', metro: 'Phoenix metro' },
  { slug: 'glendale', label: 'Glendale', state: 'Arizona', stateAbbr: 'AZ', population: '248K', metro: 'Phoenix metro' },
  { slug: 'reno', label: 'Reno', state: 'Nevada', stateAbbr: 'NV', population: '256K', metro: 'Reno metro' },
  { slug: 'hialeah', label: 'Hialeah', state: 'Florida', stateAbbr: 'FL', population: '223K', metro: 'South Florida' },
  { slug: 'irvine', label: 'Irvine', state: 'California', stateAbbr: 'CA', population: '308K', metro: 'Orange County' },
  { slug: 'chesapeake', label: 'Chesapeake', state: 'Virginia', stateAbbr: 'VA', population: '245K', metro: 'Hampton Roads' },
  { slug: 'spokane', label: 'Spokane', state: 'Washington', stateAbbr: 'WA', population: '222K', metro: 'Spokane metro' },
  { slug: 'gilbert', label: 'Gilbert', state: 'Arizona', stateAbbr: 'AZ', population: '268K', metro: 'Phoenix metro' },
  { slug: 'fremont', label: 'Fremont', state: 'California', stateAbbr: 'CA', population: '231K', metro: 'Bay Area' },
  { slug: 'tacoma', label: 'Tacoma', state: 'Washington', stateAbbr: 'WA', population: '219K', metro: 'Puget Sound' },
  { slug: 'san-bernardino', label: 'San Bernardino', state: 'California', stateAbbr: 'CA', population: '217K', metro: 'Inland Empire' },
  { slug: 'irving', label: 'Irving', state: 'Texas', stateAbbr: 'TX', population: '257K', metro: 'DFW metro' },
  { slug: 'boise', label: 'Boise', state: 'Idaho', stateAbbr: 'ID', population: '236K', metro: 'Boise metro' },
  { slug: 'rochester', label: 'Rochester', state: 'New York', stateAbbr: 'NY', population: '206K', metro: 'Rochester metro' },
  { slug: 'fayetteville', label: 'Fayetteville', state: 'North Carolina', stateAbbr: 'NC', population: '212K', metro: 'Fayetteville metro' },
  { slug: 'des-moines', label: 'Des Moines', state: 'Iowa', stateAbbr: 'IA', population: '214K', metro: 'Des Moines metro' },
  { slug: 'akron', label: 'Akron', state: 'Ohio', stateAbbr: 'OH', population: '190K', metro: 'Akron metro' },
  { slug: 'yonkers', label: 'Yonkers', state: 'New York', stateAbbr: 'NY', population: '212K', metro: 'NYC metro' },
  { slug: 'montgomery', label: 'Montgomery', state: 'Alabama', stateAbbr: 'AL', population: '200K', metro: 'Montgomery metro' },
  { slug: 'glendale-ca', label: 'Glendale', state: 'California', stateAbbr: 'CA', population: '196K', metro: 'LA metro' },
  { slug: 'huntington-beach', label: 'Huntington Beach', state: 'California', stateAbbr: 'CA', population: '198K', metro: 'Orange County' },
  { slug: 'tempe', label: 'Tempe', state: 'Arizona', stateAbbr: 'AZ', population: '195K', metro: 'Phoenix metro' },
  { slug: 'knoxville', label: 'Knoxville', state: 'Tennessee', stateAbbr: 'TN', population: '190K', metro: 'Knoxville metro' },
]

// Helper: get industry by slug
export function getIndustry(slug: string): Industry | undefined {
  return INDUSTRIES.find((i) => i.slug === slug)
}

// Helper: get city by slug
export function getCity(slug: string): City | undefined {
  return CITIES.find((c) => c.slug === slug)
}

// All valid [industry, city] slug pairs for generateStaticParams
export function getAllPairs(): { industry: string; city: string }[] {
  return INDUSTRIES.flatMap((i) =>
    CITIES.map((c) => ({ industry: i.slug, city: c.slug }))
  )
}
